services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: svelysia
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  openobserve:
    # container_name: openobserve
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "luanbt21@gmail.com"
      ZO_ROOT_USER_PASSWORD: "123456"
    ports:
      - "5080:5080"
    volumes:
      - openobserve_data:/dataopentelemetry

volumes:
  openobserve_data:
  postgres_data:
