//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
export type User = $ModelResult<$Schema, "User">;
export type Session = $ModelResult<$Schema, "Session">;
export type Account = $ModelResult<$Schema, "Account">;
export type Verification = $ModelResult<$Schema, "Verification">;
export type Tree = $ModelResult<$Schema, "Tree">;
export type TreeMember = $ModelResult<$Schema, "TreeMember">;
export type Node = $ModelResult<$Schema, "Node">;
export type CustomField = $ModelResult<$Schema, "CustomField">;
export type CustomFieldValue = $ModelResult<$Schema, "CustomFieldValue">;
export type CustomKinshipTerm = $ModelResult<$Schema, "CustomKinshipTerm">;
export type Edge = $ModelResult<$Schema, "Edge">;
export const Gender = $schema.enums.Gender.values;
export type Gender = (typeof Gender)[keyof typeof Gender];
export const EdgeType = $schema.enums.EdgeType.values;
export type EdgeType = (typeof EdgeType)[keyof typeof EdgeType];
